/****************************************************************************
 *
 * CRI Middleware SDK
 *
 * Copyright (c) 2020 CRI Middleware Co., Ltd.
 *
 * Library  : Aeropoint Lite Runtime
 * Module   : Library System Header
 * File     : cri_aero_config_ais_reference.h
 *
 ****************************************************************************/

/* Prevention of redefinition    */
#ifndef CRI_AERO_CONFIG_AIS_H
#define CRI_AERO_CONFIG_AIS_H

/* Include device information */
#include "platform.h"
#include "r_glcdc_rx_config.h"


#if defined(QE_AEROPOINT_CONFIGURATION)
/*
 *  Header file generated by QE for Display[RX]
 *  Enabled when using QE for Display[RX]
 *  QE for Display[RX] adds the macro definition "QE_AEROPOINT_CONFIGURATION" to the compile options.
 */
#include "qe_aeropoint_config.h"

#else

#if defined(BSP_MCU_RX65N)

/* for RX65N Envision kit */

/*****************************************************************************
 * Macros of constant value
 *****************************************************************************/

#define CRI_AERO_CONFIG_AIS_LCD_WIDTH           (480)
#define CRI_AERO_CONFIG_AIS_LCD_HEIGHT          (272)

#define CRI_AERO_CONFIG_AIS_FRAME_BUFFER_1      (0x0001DE00)
#define CRI_AERO_CONFIG_AIS_FRAME_BUFFER_2      (0x00800000)
#define CRI_AERO_CONFIG_AIS_AERODATA            (0x00822080)

#define CRI_AERO_CONFIG_AIS_USE_SD              (0)
#define CRI_AERO_CONFIG_AIS_USE_FLASH           (0)
#define CRI_AERO_CONFIG_AIS_USE_DAMP            (0)
#define CRI_AERO_CONFIG_AIS_USE_LAN             (0)
#define CRI_AERO_CONFIG_AIS_USE_COMMAND_UART    (0)
#define CRI_AERO_CONFIG_AIS_USE_COMMAND_TOUCH   (1)

 /* LCD Module */
#define CRI_AERO_PIN_USE_LCD_BACK_LIGHT         (1)
#define CRI_AERO_PIN_CONFIG_LCD_BACK_LIGHT      (GPIO_PORT_6_PIN_6)

#define CRI_AERO_PIN_USE_LCD_DISPLAY            (1)
#define CRI_AERO_PIN_CONFIG_LCD_DISPLAY         (GPIO_PORT_6_PIN_3)

/* Touch Module */
#define CRI_AERO_USE_CH_TOUCH_MODULE            (6)
#define CRI_AERO_SLV_ADDRESS_TOUCH_MODULE       (0x38)

#define CRI_AERO_PIN_USE_TOUCH_MODULE           (1)
#define CRI_AERO_PIN_CONFIG_TOUCH_MODULE        (GPIO_PORT_0_PIN_7)

/* SD Card */
#define CRI_AERO_PIN_USE_SDHI_POWER             (1)
#define CRI_AERO_PIN_ACTIVE_SDHI_POWER          (1)
#define CRI_AERO_PIN_CONFIG_SDHI_POWER          (GPIO_PORT_6_PIN_4)

/* LAN */
#define CRI_AERO_USE_CH_LAN                     (0)

/* UART */
#define CRI_AERO_USE_CH_COMMAND_UART            (2)

/* DAMP */
#define CRI_AERO_DAMP_PERIPHERAL                (MTU)
#define CRI_AERO_PIN_CONFIG_DAMP_A              (GPIO_PORT_5_PIN_5)
#define CRI_AERO_PIN_CONFIG_DAMP_B              (GPIO_PORT_B_PIN_6)



#elif defined(BSP_MCU_RX72N)

/* for RX72N Envision kit */

/*****************************************************************************
 * Macros of constant value
 *****************************************************************************/

#define CRI_AERO_CONFIG_AIS_LCD_WIDTH           (480)
#define CRI_AERO_CONFIG_AIS_LCD_HEIGHT          (272)

#define CRI_AERO_CONFIG_AIS_FRAME_BUFFER_1      (0x0003C000)
#define CRI_AERO_CONFIG_AIS_FRAME_BUFFER_2      (0x0005E000)
#define CRI_AERO_CONFIG_AIS_AERODATA            (0x00800000)

#define CRI_AERO_CONFIG_AIS_USE_SD              (0)
#define CRI_AERO_CONFIG_AIS_USE_FLASH           (0)
#define CRI_AERO_CONFIG_AIS_USE_DAMP            (0)
#define CRI_AERO_CONFIG_AIS_USE_LAN             (0)
#define CRI_AERO_CONFIG_AIS_USE_COMMAND_UART    (0)
#define CRI_AERO_CONFIG_AIS_USE_COMMAND_TOUCH   (1)

 /* LCD Module */
#define CRI_AERO_PIN_USE_LCD_BACK_LIGHT         (1)
#define CRI_AERO_PIN_CONFIG_LCD_BACK_LIGHT      (GPIO_PORT_6_PIN_7)

#define CRI_AERO_PIN_USE_LCD_DISPLAY            (1)
#define CRI_AERO_PIN_CONFIG_LCD_DISPLAY         (GPIO_PORT_B_PIN_3)

/* Touch Module */
#define CRI_AERO_USE_CH_TOUCH_MODULE            (6)
#define CRI_AERO_SLV_ADDRESS_TOUCH_MODULE       (0x38)

#define CRI_AERO_PIN_USE_TOUCH_MODULE           (1)
#define CRI_AERO_PIN_CONFIG_TOUCH_MODULE        (GPIO_PORT_6_PIN_6)

/* SD Card */
#define CRI_AERO_PIN_USE_SDHI_POWER             (1)
#define CRI_AERO_PIN_ACTIVE_SDHI_POWER          (1)
#define CRI_AERO_PIN_CONFIG_SDHI_POWER          (GPIO_PORT_4_PIN_2)

/* LAN */
#define CRI_AERO_USE_CH_LAN                     (0)

/* UART */
#define CRI_AERO_USE_CH_COMMAND_UART            (2)

/* DAMP */
#define CRI_AERO_DAMP_PERIPHERAL                (GPTW)
#define CRI_AERO_DAMP_GPTW_CH                   (1)
#define CRI_AERO_PIN_CONFIG_DAMP_A              (GPIO_PORT_D_PIN_1)
#define CRI_AERO_PIN_CONFIG_DAMP_B              (GPIO_PORT_D_PIN_0)
#define CRI_AERO_DAMP_GPTW_INT_TABLE            (255)



#elif defined(BSP_MCU_RX72M) || defined(BSP_MCU_RX66N)

/* for RX72M and RX66N User System */
/* Set cri_aero_config_ais.h file according to the user system. */

/*****************************************************************************
 * Macros of constant value
 *****************************************************************************/

#define CRI_AERO_CONFIG_AIS_LCD_WIDTH           (480)
#define CRI_AERO_CONFIG_AIS_LCD_HEIGHT          (272)

#define CRI_AERO_CONFIG_AIS_FRAME_BUFFER_1      (0x0003C000)
#define CRI_AERO_CONFIG_AIS_FRAME_BUFFER_2      (0x0005E000)
#define CRI_AERO_CONFIG_AIS_AERODATA            (0x00800000)

#define CRI_AERO_CONFIG_AIS_USE_SD              (0)
#define CRI_AERO_CONFIG_AIS_USE_FLASH           (0)
#define CRI_AERO_CONFIG_AIS_USE_DAMP            (0)
#define CRI_AERO_CONFIG_AIS_USE_LAN             (0)
#define CRI_AERO_CONFIG_AIS_USE_COMMAND_UART    (0)
#define CRI_AERO_CONFIG_AIS_USE_COMMAND_TOUCH   (1)

 /* LCD Module */
#define CRI_AERO_PIN_USE_LCD_BACK_LIGHT         (1)
#define CRI_AERO_PIN_CONFIG_LCD_BACK_LIGHT      (GPIO_PORT_6_PIN_7)

#define CRI_AERO_PIN_USE_LCD_DISPLAY            (1)
#define CRI_AERO_PIN_CONFIG_LCD_DISPLAY         (GPIO_PORT_B_PIN_3)

/* Touch Module */
#define CRI_AERO_USE_CH_TOUCH_MODULE            (6)
#define CRI_AERO_SLV_ADDRESS_TOUCH_MODULE       (0x38)

#define CRI_AERO_PIN_USE_TOUCH_MODULE           (1)
#define CRI_AERO_PIN_CONFIG_TOUCH_MODULE        (GPIO_PORT_6_PIN_6)

/* SD Card */
#define CRI_AERO_PIN_USE_SDHI_POWER             (1)
#define CRI_AERO_PIN_ACTIVE_SDHI_POWER          (1)
#define CRI_AERO_PIN_CONFIG_SDHI_POWER          (GPIO_PORT_4_PIN_2)

/* LAN */
#define CRI_AERO_USE_CH_LAN                     (0)

/* UART */
#define CRI_AERO_USE_CH_COMMAND_UART            (2)

/* DAMP */
#define CRI_AERO_DAMP_PERIPHERAL                (GPTW)
#define CRI_AERO_DAMP_GPTW_CH                   (1)
#define CRI_AERO_PIN_CONFIG_DAMP_A              (GPIO_PORT_D_PIN_1)
#define CRI_AERO_PIN_CONFIG_DAMP_B              (GPIO_PORT_D_PIN_0)
#define CRI_AERO_DAMP_GPTW_INT_TABLE            (255)



#else

#error Unsupported BSP_MCU

#endif

#endif /* QE_AEROPOINT_CONFIGURATION */

#endif /* CRI_AERO_CONFIG_AIS_H */

/* --- end of file --- */

