/* Generated configuration header file - do not edit */
/***********************************************************************************************************************
 * Copyright [2020-2022] Renesas Electronics Corporation and/or its affiliates.  All Rights Reserved.
 *
 * This software and documentation are supplied by Renesas Electronics America Inc. and may only be used with products
 * of Renesas Electronics Corp. and its affiliates ("Renesas").  No other uses are authorized.  Renesas products are
 * sold pursuant to Renesas terms and conditions of sale.  Purchasers are solely responsible for the selection and use
 * of Renesas products and Renesas assumes no liability.  No license, express or implied, to any intellectual property
 * right is granted by Renesas. This software is protected under all applicable laws, including copyright laws. Renesas
 * reserves the right to change or discontinue this software and/or this documentation. THE SOFTWARE AND DOCUMENTATION
 * IS DELIVERED TO YOU "AS IS," AND RENESAS MAKES NO REPRESENTATIONS OR WARRANTIES, AND TO THE FULLEST EXTENT
 * PERMISSIBLE UNDER APPLICABLE LAW, DISCLAIMS ALL WARRANTIES, WHETHER EXPLICITLY OR IMPLICITLY, INCLUDING WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT, WITH RESPECT TO THE SOFTWARE OR
 * DOCUMENTATION.  RENESAS SHALL HAVE NO LIABILITY ARISING OUT OF ANY SECURITY VULNERABILITY OR BREACH.  TO THE MAXIMUM
 * EXTENT PERMITTED BY LAW, IN NO EVENT WILL RENESAS BE LIABLE TO YOU IN CONNECTION WITH THE SOFTWARE OR DOCUMENTATION
 * (OR ANY PERSON OR ENTITY CLAIMING RIGHTS DERIVED FROM YOU) FOR ANY LOSS, DAMAGES, OR CLAIMS WHATSOEVER, INCLUDING,
 * WITHOUT LIMITATION, ANY DIRECT, CONSEQUENTIAL, SPECIAL, INDIRECT, PUNITIVE, OR INCIDENTAL DAMAGES; ANY LOST PROFITS,
 * OTHER ECONOMIC DAMAGE, PROPERTY DAMAGE, OR PERSONAL INJURY; AND EVEN IF RENESAS HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH LOSS, DAMAGES, CLAIMS OR COSTS.
 **********************************************************************************************************************/

/* Guards against multiple inclusion */
#ifndef R_OB1203_CONFIG_H
#define R_OB1203_CONFIG_H
/***********************************************************************************************************************
 Configuration Options
 **********************************************************************************************************************/

/* SPECIFY WHETHER TO INCLUDE CODE FOR API PARAMETER CHECKING */
/* Setting to BSP_CFG_PARAM_CHECKING_ENABLE utilizes the system default setting */
/* Setting to 1 includes parameter checking */
/* Setting to 0 does not include parameter checking */
#define RM_OB1203_CFG_PARAM_CHECKING_ENABLE             (BSP_CFG_PARAM_CHECKING_ENABLE)

/* SPECIFY NUMBER OF DEVICES */
#define RM_OB1203_CFG_DEVICE_NUM_MAX                    (1) /* Number (max.) of OB1203 Sensors */

/* SPECIFY USING COMMUNICATION LINE INSTANCE FOP DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_COMMS_INSTANCE            (g_comms_i2c_device0)

/* SPECIFY I2C CALLBACK FUNCTION NAME FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_COMMS_I2C_CALLBACK        (ob1203_user_i2c_callback0) /* Enable user I2C callback for OB1203 Sensor Device0 */

/* SPECIFY IRQ ENABLED FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_IRQ_ENABLE                (0)

/* SPECIFY IRQ CALLBACK FUNCTION NAME FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_IRQ_CALLBACK              (ob1203_user_irq_callback0) /* Enable user IRQ callback for OB1203 Sensor Device0 */

/* SPECIFY IRQ NUMBER FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_IRQ_NUMBER                (IRQ_NUM_13)

/* SPECIFY IRQ TRIGGER FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_IRQ_TRIGGER               (IRQ_TRIG_RISING)

/* SPECIFY IRQ PRIORITY FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_IRQ_PRIORITY              (IRQ_PRI_10)

/* SPECIFY SEMAPHORE TIMEOUT FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_SEMAPHORE_TIMEOUT         (0xFFFFFFFF)

/* SPECIFY OPERATION MODE FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_SENSOR_MODE                (1) /* Set operation mode of OB1203 Sensors device0 */
                                                            /*
                                                            0 : Not selected
                                                            1 : Light Sensor mode
                                                            2 : Proximity Sensor mode
                                                            3 : Light Proximity Sensor mode
                                                            4 : PPG Sensor mode
                                                             */

/* SPECIFY LIGHT PROX DEVICE INTERRUPT FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_LIGHT_PROX_DEVICE_INTERRUPT   (RM_OB1203_OPERATION_MODE_STANDBY)

/* SPECIFY PPG PROX GAIN FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PPG_PROX_GAIN          (RM_OB1203_PPG_PROX_GAIN_1)

/* SPECIFY PROX LED ORDER FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_LED_ORDER                   (RM_OB1203_LED_IR_FIRST_RED_SECOND)

/* SPECIFY LIGHT MODE FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_LIGHT_SENSOR_MODE           (RM_OB1203_LIGHT_SENSOR_MODE_LS)

/* SPECIFY LIGHT INTERRUPT TYPE FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_LIGHT_INTERRUPT_TYPE        (RM_OB1203_LIGHT_INTERRUPT_TYPE_THRESHOLD)

/* SPECIFY LIGHT INTERRUPT SOURCE FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_LIGHT_INTERRUPT_SOURCE      (RM_OB1203_LIGHT_INTERRUPT_SOURCE_CLEAR_CHANNEL)

/* SPECIFY LIGHT INTERRUPT PERSIST FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_LIGHT_INTERRUPT_PERSIST     (0x02)

/* SPECIFY LIGHT SPEEP AFTER INTERRUPT FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_LIGHT_SLEEP_AFTER_INTERRUPT (RM_OB1203_SLEEP_AFTER_INTERRUPT_DISABLE)

/* SPECIFY LIGHT GAIN FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_LIGHT_GAIN                  (RM_OB1203_LIGHT_GAIN_3)

/* SPECIFY LIGHT RESOLUTION PERIPD FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_LIGHT_RESOLUTION_PERIOD     (RM_OB1203_LIGHT_RESOLUTION_18BIT_PERIOD_100MS)

/* SPECIFY LIGHT UPPER THRESHOLD FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_LIGHT_UPPER_THRESHOLD             (0x00CCC)

/* SPECIFY LIGHT LOWER THRESHOLD FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_LIGHT_LOWER_THRESHOLD             (0x00000)

/* SPECIFY LIGHT VARIANCE THRESHOLD FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_LIGHT_VARIANCE_THRESHOLD          (RM_OB1203_VARIANCE_THRESHOLD_128_COUNTS)

/* SPECIFY PROX INTERRUPT TYPE FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PROX_INTERRUPT_TYPE         (RM_OB1203_PROX_INTERRUPT_TYPE_NORMAL)

/* SPECIFY PROX INTERRUPT PERSIST FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PROX_INTERRUPT_PERSIST      (0x02)

/* SPECIFY PROX SPEEP AFTER INTERRUPT FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PROX_SLEEP_AFTER_INTERRUPT  (RM_OB1203_SLEEP_AFTER_INTERRUPT_DISABLE)

/* SPECIFY PROX LED CURRENT FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PROX_LED_CURRENT            (0x100)

/* SPECIFY PROX LED ANALOG CANCELLATION FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PROX_ANA_CAN                (RM_OB1203_ANALOG_CANCELLATION_DISABLE)

/* SPECIFY PROX LED DIGITAL CANCELLATION FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PROX_DIG_CAN                (0x100)

/* SPECIFY PROX LED PULSES NUMBER FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PROX_NUM_LED_PULSES         (RM_OB1203_NUM_LED_PULSES_8)

/* SPECIFY PROX PULSE WIDTH AND MEASUREMENT PERIOD FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PROX_WIDTH_PERIOD           (RM_OB1203_PROX_WIDTH_42US_PERIOD_100MS)

/* SPECIFY PROX MOVING AVERAGE FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PROX_MOVING_AVERAGE         (RM_OB1203_MOVING_AVERAGE_DISABLE)

/* SPECIFY PROX HYSTERESIS FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PROX_HYSTERESIS             (0x00)

/* SPECIFY PROX UPPER THRESHOLD FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PROX_UPPER_THRESHOLD        (0x0600)

/* SPECIFY PROX LOWER THRESHOLD FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PROX_LOWER_THRESHOLD        (0x0000)

/* SPECIFY PPG MODE FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PPG_SENSOR_MODE             (RM_OB1203_PPG_SENSOR_SENSOR_MODE_PPG2)

/* SPECIFY PPG INTERRUPT TYPE FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PPG_INTERRUPT_TYPE          (RM_OB1203_PPG_INTERRUPT_TYPE_DATA)

/* SPECIFY PPG IR LED CURRENT FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PPG_IR_LED_CURRENT          (0x366)

/* SPECIFY PPG RED LED CURRENT FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PPG_RED_LED_CURRENT         (0x1B3)

/* SPECIFY PPG POWER SAVE MODE FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PPG_POWER_SAVE_MODE         (RM_OB1203_POWER_SAVE_MODE_DISABLE)

/* SPECIFY PPG IR LED ANALOG CANCELLATION FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PPG_IR_LED_ANA_CAN          (RM_OB1203_ANALOG_CANCELLATION_DISABLE)

/* SPECIFY PPG RED LED ANALOG CANCELLATION FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PPG_RED_LED_ANA_CAN         (RM_OB1203_ANALOG_CANCELLATION_DISABLE)

/* SPECIFY PPG NUMBER OF AVERAGED PPG SAMPLES FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PPG_NUM_AVERAGED_SAMPLES    (RM_OB1203_NUM_AVERAGED_SAMPLES_8)

/* SPECIFY PPG PULSE WIDTH AND MEASUREMENT PERIOD FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PPG_WIDTH_PERIOD            (RM_OB1203_PPG_WIDTH_130US_PERIOD_1P25MS)

/* SPECIFY PPG FIFO ROLLOVER FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PPG_FIFO_ROLLOVER           (RM_OB1203_FIFO_ROLLOVER_ENABLE)

/* SPECIFY PPG FIFO ALMOST FULL VALUE FOR DEVICE0 */
#define RM_OB1203_CFG_DEVICE0_PPG_FIFO_EMPTY_NUM          (0x0C)

/* SPECIFY USING COMMUNICATION LINE INSTANCE FOP DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_COMMS_INSTANCE            (g_comms_i2c_device1)

/* SPECIFY I2C CALLBACK FUNCTION NAME FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_COMMS_I2C_CALLBACK        (ob1203_user_i2c_callback1) /* Enable user I2C callback for OB1203 Sensor Device1 */

/* SPECIFY IRQ ENABLED FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_IRQ_ENABLE                (0)

/* SPECIFY IRQ CALLBACK FUNCTION NAME FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_IRQ_CALLBACK              (ob1203_user_irq_callback1) /* Enable user IRQ callback for OB1203 Sensor Device1 */

/* SPECIFY IRQ NUMBER FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_IRQ_NUMBER                (IRQ_NUM_13)

/* SPECIFY IRQ TRIGGER FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_IRQ_TRIGGER               (IRQ_TRIG_RISING)

/* SPECIFY IRQ PRIORITY FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_IRQ_PRIORITY              (IRQ_PRI_10)

/* SPECIFY SEMAPHORE TIMEOUT FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_SEMAPHORE_TIMEOUT         (0xFFFFFFFF)

/* SPECIFY OPERATION MODE FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_SENSOR_MODE                (1) /* Set operation mode of OB1203 Sensors device1 */
                                                            /*
                                                            0 : Not selected
                                                            1 : Light Sensor mode
                                                            2 : Proximity Sensor mode
                                                            3 : Light Proximity Sensor mode
                                                            4 : PPG Sensor mode
                                                             */

/* SPECIFY LIGHT PROX DEVICE INTERRUPT FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_LIGHT_PROX_DEVICE_INTERRUPT   (RM_OB1203_OPERATION_MODE_STANDBY)

/* SPECIFY PPG PROX GAIN FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PPG_PROX_GAIN               (RM_OB1203_PPG_PROX_GAIN_1)

/* SPECIFY PROX LED ORDER FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_LED_ORDER                   (RM_OB1203_LED_IR_FIRST_RED_SECOND)

/* SPECIFY LIGHT MODE FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_LIGHT_SENSOR_MODE           (RM_OB1203_LIGHT_SENSOR_MODE_LS)

/* SPECIFY LIGHT INTERRUPT TYPE FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_LIGHT_INTERRUPT_TYPE        (RM_OB1203_LIGHT_INTERRUPT_TYPE_THRESHOLD)

/* SPECIFY LIGHT INTERRUPT SOURCE FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_LIGHT_INTERRUPT_SOURCE      (RM_OB1203_LIGHT_INTERRUPT_SOURCE_CLEAR_CHANNEL)

/* SPECIFY LIGHT INTERRUPT PERSIST FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_LIGHT_INTERRUPT_PERSIST     (0x02)

/* SPECIFY LIGHT SPEEP AFTER INTERRUPT FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_LIGHT_SLEEP_AFTER_INTERRUPT (RM_OB1203_SLEEP_AFTER_INTERRUPT_DISABLE)

/* SPECIFY LIGHT GAIN FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_LIGHT_GAIN                  (RM_OB1203_LIGHT_GAIN_3)

/* SPECIFY LIGHT RESOLUTION PERIPD FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_LIGHT_RESOLUTION_PERIOD           (RM_OB1203_LIGHT_RESOLUTION_18BIT_PERIOD_100MS)

/* SPECIFY LIGHT UPPER THRESHOLD FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_LIGHT_UPPER_THRESHOLD             (0x00CCC)

/* SPECIFY LIGHT LOWER THRESHOLD FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_LIGHT_LOWER_THRESHOLD             (0x00000)

/* SPECIFY LIGHT VARIANCE THRESHOLD FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_LIGHT_VARIANCE_THRESHOLD          (RM_OB1203_VARIANCE_THRESHOLD_128_COUNTS)

/* SPECIFY PROX INTERRUPT TYPE FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PROX_INTERRUPT_TYPE         (RM_OB1203_PROX_INTERRUPT_TYPE_NORMAL)

/* SPECIFY PROX INTERRUPT PERSIST FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PROX_INTERRUPT_PERSIST      (0x02)

/* SPECIFY PROX SPEEP AFTER INTERRUPT FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PROX_SLEEP_AFTER_INTERRUPT  (RM_OB1203_SLEEP_AFTER_INTERRUPT_DISABLE)

/* SPECIFY PROX LED CURRENT FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PROX_LED_CURRENT            (0x100)

/* SPECIFY PROX LED ANALOG CANCELLATION FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PROX_ANA_CAN                (RM_OB1203_ANALOG_CANCELLATION_DISABLE)

/* SPECIFY PROX LED DIGITAL CANCELLATION FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PROX_DIG_CAN                (0x100)

/* SPECIFY PROX LED PULSES NUMBER FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PROX_NUM_LED_PULSES         (RM_OB1203_NUM_LED_PULSES_8)

/* SPECIFY PROX PULSE WIDTH AND MEASUREMENT PERIOD FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PROX_WIDTH_PERIOD           (RM_OB1203_PROX_WIDTH_42US_PERIOD_100MS)

/* SPECIFY PROX MOVING AVERAGE FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PROX_MOVING_AVERAGE         (RM_OB1203_MOVING_AVERAGE_DISABLE)

/* SPECIFY PROX HYSTERESIS FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PROX_HYSTERESIS             (0x00)

/* SPECIFY PROX UPPER THRESHOLD FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PROX_UPPER_THRESHOLD        (0x0600)

/* SPECIFY PROX LOWER THRESHOLD FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PROX_LOWER_THRESHOLD        (0x0000)

/* SPECIFY PPG MODE FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PPG_SENSOR_MODE             (RM_OB1203_PPG_SENSOR_SENSOR_MODE_PPG2)

/* SPECIFY PPG INTERRUPT TYPE FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PPG_INTERRUPT_TYPE          (RM_OB1203_PPG_INTERRUPT_TYPE_DATA)

/* SPECIFY PPG IR LED CURRENT FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PPG_IR_LED_CURRENT          (0x366)

/* SPECIFY PPG RED LED CURRENT FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PPG_RED_LED_CURRENT         (0x1B3)

/* SPECIFY PPG POWER SAVE MODE FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PPG_POWER_SAVE_MODE         (RM_OB1203_POWER_SAVE_MODE_DISABLE)

/* SPECIFY PPG IR LED ANALOG CANCELLATION FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PPG_IR_LED_ANA_CAN          (RM_OB1203_ANALOG_CANCELLATION_DISABLE)

/* SPECIFY PPG RED LED ANALOG CANCELLATION FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PPG_RED_LED_ANA_CAN         (RM_OB1203_ANALOG_CANCELLATION_DISABLE)

/* SPECIFY PPG NUMBER OF AVERAGED PPG SAMPLES FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PPG_NUM_AVERAGED_SAMPLES    (RM_OB1203_NUM_AVERAGED_SAMPLES_8)

/* SPECIFY PPG PULSE WIDTH AND MEASUREMENT PERIOD FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PPG_WIDTH_PERIOD            (RM_OB1203_PPG_WIDTH_130US_PERIOD_1P25MS)

/* SPECIFY PPG FIFO ROLLOVER FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PPG_FIFO_ROLLOVER           (RM_OB1203_FIFO_ROLLOVER_ENABLE)

/* SPECIFY PPG FIFO ALMOST FULL VALUE FOR DEVICE1 */
#define RM_OB1203_CFG_DEVICE1_PPG_FIFO_EMPTY_NUM          (0x0C)

#if RM_OB1203_CFG_DEVICE0_IRQ_ENABLE || RM_OB1203_CFG_DEVICE1_IRQ_ENABLE
#define RM_OB1203_CFG_IRQ_ENABLE (1)
#else
#define RM_OB1203_CFG_IRQ_ENABLE (0)
#endif

#if (RM_OB1203_CFG_DEVICE0_SENSOR_MODE == 1) || (RM_OB1203_CFG_DEVICE1_SENSOR_MODE == 1)
#define RM_OB1203_LIGHT_MODE_ENABLE (1)
#else
#define RM_OB1203_LIGHT_MODE_ENABLE (0)
#endif

#if (RM_OB1203_CFG_DEVICE0_SENSOR_MODE == 2) || (RM_OB1203_CFG_DEVICE1_SENSOR_MODE == 2)
#define RM_OB1203_PROXIMITY_MODE_ENABLE (1)
#else
#define RM_OB1203_PROXIMITY_MODE_ENABLE (0)
#endif

#if (RM_OB1203_CFG_DEVICE0_SENSOR_MODE == 3) || (RM_OB1203_CFG_DEVICE1_SENSOR_MODE == 3)
#define RM_OB1203_LIGHT_PROX_MODE_ENABLE (1)
#else
#define RM_OB1203_LIGHT_PROX_MODE_ENABLE (0)
#endif

#if (RM_OB1203_CFG_DEVICE0_SENSOR_MODE == 4) || (RM_OB1203_CFG_DEVICE1_SENSOR_MODE == 4)
#define RM_OB1203_PPG_MODE_ENABLE (1)
#else
#define RM_OB1203_PPG_MODE_ENABLE (0)
#endif

#endif  /* R_OB1203_CONFIG_H */
