/***********************************************************************************************************************
 * Copyright [2023] Renesas Electronics Corporation and/or its affiliates.  All Rights Reserved.
 *
 * This software and documentation are supplied by Renesas Electronics America Inc. and may only be used with products
 * of Renesas Electronics Corp. and its affiliates ("Renesas").  No other uses are authorized.  Renesas products are
 * sold pursuant to Renesas terms and conditions of sale.  Purchasers are solely responsible for the selection and use
 * of Renesas products and Renesas assumes no liability.  No license, express or implied, to any intellectual property
 * right is granted by Renesas. This software is protected under all applicable laws, including copyright laws. Renesas
 * reserves the right to change or discontinue this software and/or this documentation. THE SOFTWARE AND DOCUMENTATION
 * IS DELIVERED TO YOU "AS IS," AND RENESAS MAKES NO REPRESENTATIONS OR WARRANTIES, AND TO THE FULLEST EXTENT
 * PERMISSIBLE UNDER APPLICABLE LAW, DISCLAIMS ALL WARRANTIES, WHETHER EXPLICITLY OR IMPLICITLY, INCLUDING WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT, WITH RESPECT TO THE SOFTWARE OR
 * DOCUMENTATION.  RENESAS SHALL HAVE NO LIABILITY ARISING OUT OF ANY SECURITY VULNERABILITY OR BREACH.  TO THE MAXIMUM
 * EXTENT PERMITTED BY LAW, IN NO EVENT WILL RENESAS BE LIABLE TO YOU IN CONNECTION WITH THE SOFTWARE OR DOCUMENTATION
 * (OR ANY PERSON OR ENTITY CLAIMING RIGHTS DERIVED FROM YOU) FOR ANY LOSS, DAMAGES, OR CLAIMS WHATSOEVER, INCLUDING,
 * WITHOUT LIMITATION, ANY DIRECT, CONSEQUENTIAL, SPECIAL, INDIRECT, PUNITIVE, OR INCIDENTAL DAMAGES; ANY LOST PROFITS,
 * OTHER ECONOMIC DAMAGE, PROPERTY DAMAGE, OR PERSONAL INJURY; AND EVEN IF RENESAS HAS BEEN ADVISED OF THE POSSIBILITY
 * OF SUCH LOSS, DAMAGES, CLAIMS OR COSTS.
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Includes
 **********************************************************************************************************************/
#include "rm_rai_data_collector.h"

/***********************************************************************************************************************
 * Macro definitions
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Typedef definitions
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Private function prototypes
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Private global variables
 **********************************************************************************************************************/

/***********************************************************************************************************************
 * Global function prototypes
 **********************************************************************************************************************/
extern void rm_rai_data_collector_dtc_end_cb          (rai_data_collector_ctrl_t                const * p_api_ctrl);
/* RAI Data Collector0 */
void rm_rai_data_collector_dc0_timer_callback         (void                                           * pdata);
void RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_READY_CALLBACK(rai_data_collector_callback_args_t       const * p_args);
void RM_RAI_DATA_COLLECTOR_CFG_DC0_ERROR_CALLBACK     (rai_data_collector_error_callback_args_t const * p_args);

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
/* RAI Data Collector0 */
/* Timer */
timer_instance_t g_rai_data_collector0_timer =
{
    .freqency_hz = RM_RAI_DATA_COLLECTOR_CFG_DC0_TIMER_FREQUENCY,
    .channel     = RM_RAI_DATA_COLLECTOR_CFG_DC0_TIMER_CHANNEL,
    .priority    = RM_RAI_DATA_COLLECTOR_CFG_DC0_TIMER_PRIORITY,
    .callback    = rm_rai_data_collector_dc0_timer_callback,
};

/* DTC */
#define RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH (RM_RAI_DATA_COLLECTOR_CFG_DC0_FRAME_BUF_LEN * RAI_DATA_COLLECTOR_PING_PONG_BUFFER_SIZE)
#define RM_RAI_DATA_COLLECTOR_DC0_CHANNELS                (RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS + RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
#define RM_RAI_DATA_COLLECTOR_DC0_VIRT_CHANNELS           (RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS + 1)

#if (1 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
double 
#endif
g_rai_data_collector0_snapshot_channel0_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (2 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
double 
#endif
g_rai_data_collector0_snapshot_channel1_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (3 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
double 
#endif
g_rai_data_collector0_snapshot_channel2_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (4 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
double 
#endif
g_rai_data_collector0_snapshot_channel3_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (5 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
double 
#endif
g_rai_data_collector0_snapshot_channel4_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (6 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
double 
#endif
g_rai_data_collector0_snapshot_channel5_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (7 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
double 
#endif
g_rai_data_collector0_snapshot_channel6_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (8 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
double 
#endif
g_rai_data_collector0_snapshot_channel7_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif


#if (1 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
double 
#endif
g_rai_data_collector0_data_feed_channel0_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (2 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
double 
#endif
g_rai_data_collector0_data_feed_channel1_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (3 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
double 
#endif
g_rai_data_collector0_data_feed_channel2_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (4 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
double 
#endif
g_rai_data_collector0_data_feed_channel3_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (5 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
double 
#endif
g_rai_data_collector0_data_feed_channel4_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (6 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
double 
#endif
g_rai_data_collector0_data_feed_channel5_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (7 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
double 
#endif
g_rai_data_collector0_data_feed_channel6_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

#if (8 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
int8_t 
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
uint8_t 
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
int16_t 
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
uint16_t
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
int32_t  
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
uint32_t 
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
float 
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
double 
#endif
g_rai_data_collector0_data_feed_channel7_frame_buffer[RM_RAI_DATA_COLLECTOR_DC0_PING_PONG_BUFFER_LENGTH];
#endif

rai_data_collector_frame_buffer_t g_rai_data_collector0_frame_buf[RM_RAI_DATA_COLLECTOR_DC0_CHANNELS] =
{
#if (1 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_data_feed_channel0_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (2 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_data_feed_channel1_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (3 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_data_feed_channel2_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (4 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_data_feed_channel3_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (5 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_data_feed_channel4_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (6 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_data_feed_channel5_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (7 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_data_feed_channel6_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (8 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_data_feed_channel7_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (1 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_snapshot_channel0_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (2 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_snapshot_channel1_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (3 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_snapshot_channel2_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (4 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_snapshot_channel3_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (5 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_snapshot_channel4_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (6 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_snapshot_channel5_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (7 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_snapshot_channel6_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif

#if (8 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .p_buf = g_rai_data_collector0_snapshot_channel7_frame_buffer,
#if (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT8_T,
#elif (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT8_T,
#elif (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT16_T,
#elif (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT16_T,
#elif (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_INT32_T,
#elif (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_UINT32_T,
#elif (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_FLOAT,
#elif (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE)
        .data_type = RAI_DATA_COLLECTOR_DATA_TYPE_DOUBLE,
#endif
    },
#endif
};


#if (1 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
dtc_transfer_data_t g_rai_data_collector0_dtc_transfer_data[RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS];

dtc_transfer_data_cfg_t g_rai_data_collector0_dtc_transfer_data_cfg[RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS] =
{
  #if (1 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .transfer_mode         = DTC_TRANSFER_MODE_BLOCK,

    #if   ((1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE) || (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_BYTE,
    #elif ((3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE) || (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_WORD,
    #else
        .data_size             = DTC_DATA_SIZE_LWORD,
    #endif

        .src_addr_mode         = DTC_SRC_ADDR_INCR,
        .chain_transfer_enable = (1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS) ? DTC_CHAIN_TRANSFER_DISABLE : DTC_CHAIN_TRANSFER_ENABLE,
        .chain_transfer_mode   = DTC_CHAIN_TRANSFER_NORMAL,
        .response_interrupt    = DTC_INTERRUPT_AFTER_ALL_COMPLETE,
        .repeat_block_side     = DTC_REPEAT_BLOCK_SOURCE,
        .dest_addr_mode        = DTC_DES_ADDR_INCR,
        .source_addr           = (uint32_t)NULL,
        .dest_addr             = (uint32_t)&g_rai_data_collector0_snapshot_channel0_frame_buffer,
        .transfer_count        = (8 != RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL0_DATA_TYPE) ? RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT : (RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT * 2),
        .block_size            = 1,
    },
  #endif
  #if (2 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .transfer_mode         = DTC_TRANSFER_MODE_BLOCK,

    #if   ((1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE) || (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_BYTE,
    #elif ((3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE) || (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_WORD,
    #else
        .data_size             = DTC_DATA_SIZE_LWORD,
    #endif

        .src_addr_mode         = DTC_SRC_ADDR_INCR,
        .chain_transfer_enable = (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS) ? DTC_CHAIN_TRANSFER_DISABLE : DTC_CHAIN_TRANSFER_ENABLE,
        .chain_transfer_mode   = DTC_CHAIN_TRANSFER_NORMAL,
        .response_interrupt    = DTC_INTERRUPT_AFTER_ALL_COMPLETE,
        .repeat_block_side     = DTC_REPEAT_BLOCK_SOURCE,
        .dest_addr_mode        = DTC_DES_ADDR_INCR,
        .source_addr           = (uint32_t)NULL,
        .dest_addr             = (uint32_t)&g_rai_data_collector0_snapshot_channel1_frame_buffer,
        .transfer_count        = (8 != RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL1_DATA_TYPE) ? RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT : (RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT * 2),
        .block_size            = 1,
    },
  #endif
  #if (3 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .transfer_mode         = DTC_TRANSFER_MODE_BLOCK,

    #if   ((1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE) || (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_BYTE,
    #elif ((3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE) || (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_WORD,
    #else
        .data_size             = DTC_DATA_SIZE_LWORD,
    #endif

        .src_addr_mode         = DTC_SRC_ADDR_INCR,
        .chain_transfer_enable = (3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS) ? DTC_CHAIN_TRANSFER_DISABLE : DTC_CHAIN_TRANSFER_ENABLE,
        .chain_transfer_mode   = DTC_CHAIN_TRANSFER_NORMAL,
        .response_interrupt    = DTC_INTERRUPT_AFTER_ALL_COMPLETE,
        .repeat_block_side     = DTC_REPEAT_BLOCK_SOURCE,
        .dest_addr_mode        = DTC_DES_ADDR_INCR,
        .source_addr           = (uint32_t)NULL,
        .dest_addr             = (uint32_t)&g_rai_data_collector0_snapshot_channel2_frame_buffer,
        .transfer_count        = (8 != RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL2_DATA_TYPE) ? RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT : (RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT * 2),
        .block_size            = 1,
    },
  #endif
  #if (4 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .transfer_mode         = DTC_TRANSFER_MODE_BLOCK,

    #if   ((1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE) || (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_BYTE,
    #elif ((3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE) || (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_WORD,
    #else
        .data_size             = DTC_DATA_SIZE_LWORD,
    #endif

        .src_addr_mode         = DTC_SRC_ADDR_INCR,
        .chain_transfer_enable = (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS) ? DTC_CHAIN_TRANSFER_DISABLE : DTC_CHAIN_TRANSFER_ENABLE,
        .chain_transfer_mode   = DTC_CHAIN_TRANSFER_NORMAL,
        .response_interrupt    = DTC_INTERRUPT_AFTER_ALL_COMPLETE,
        .repeat_block_side     = DTC_REPEAT_BLOCK_SOURCE,
        .dest_addr_mode        = DTC_DES_ADDR_INCR,
        .source_addr           = (uint32_t)NULL,
        .dest_addr             = (uint32_t)&g_rai_data_collector0_snapshot_channel3_frame_buffer,
        .transfer_count        = (8 != RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL3_DATA_TYPE) ? RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT : (RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT * 2),
        .block_size            = 1,
    },
  #endif
  #if (5 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .transfer_mode         = DTC_TRANSFER_MODE_BLOCK,

    #if   ((1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE) || (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_BYTE,
    #elif ((3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE) || (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_WORD,
    #else
        .data_size             = DTC_DATA_SIZE_LWORD,
    #endif

        .src_addr_mode         = DTC_SRC_ADDR_INCR,
        .chain_transfer_enable = (5 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS) ? DTC_CHAIN_TRANSFER_DISABLE : DTC_CHAIN_TRANSFER_ENABLE,
        .chain_transfer_mode   = DTC_CHAIN_TRANSFER_NORMAL,
        .response_interrupt    = DTC_INTERRUPT_AFTER_ALL_COMPLETE,
        .repeat_block_side     = DTC_REPEAT_BLOCK_SOURCE,
        .dest_addr_mode        = DTC_DES_ADDR_INCR,
        .source_addr           = (uint32_t)NULL,
        .dest_addr             = (uint32_t)&g_rai_data_collector0_snapshot_channel4_frame_buffer,
        .transfer_count        = (8 != RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL4_DATA_TYPE) ? RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT : (RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT * 2),
        .block_size            = 1,
    },
  #endif
  #if (6 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .transfer_mode         = DTC_TRANSFER_MODE_BLOCK,

    #if   ((1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE) || (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_BYTE,
    #elif ((3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE) || (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_WORD,
    #else
        .data_size             = DTC_DATA_SIZE_LWORD,
    #endif

        .src_addr_mode         = DTC_SRC_ADDR_INCR,
        .chain_transfer_enable = (6 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS) ? DTC_CHAIN_TRANSFER_DISABLE : DTC_CHAIN_TRANSFER_ENABLE,
        .chain_transfer_mode   = DTC_CHAIN_TRANSFER_NORMAL,
        .response_interrupt    = DTC_INTERRUPT_AFTER_ALL_COMPLETE,
        .repeat_block_side     = DTC_REPEAT_BLOCK_SOURCE,
        .dest_addr_mode        = DTC_DES_ADDR_INCR,
        .source_addr           = (uint32_t)NULL,
        .dest_addr             = (uint32_t)&g_rai_data_collector0_snapshot_channel5_frame_buffer,
        .transfer_count        = (8 != RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL5_DATA_TYPE) ? RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT : (RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT * 2),
        .block_size            = 1,
    },
  #endif
  #if (7 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .transfer_mode         = DTC_TRANSFER_MODE_BLOCK,

    #if   ((1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE) || (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_BYTE,
    #elif ((3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE) || (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_WORD,
    #else
        .data_size             = DTC_DATA_SIZE_LWORD,
    #endif

        .src_addr_mode         = DTC_SRC_ADDR_INCR,
        .chain_transfer_enable = (7 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS) ? DTC_CHAIN_TRANSFER_DISABLE : DTC_CHAIN_TRANSFER_ENABLE,
        .chain_transfer_mode   = DTC_CHAIN_TRANSFER_NORMAL,
        .response_interrupt    = DTC_INTERRUPT_AFTER_ALL_COMPLETE,
        .repeat_block_side     = DTC_REPEAT_BLOCK_SOURCE,
        .dest_addr_mode        = DTC_DES_ADDR_INCR,
        .source_addr           = (uint32_t)NULL,
        .dest_addr             = (uint32_t)&g_rai_data_collector0_snapshot_channel6_frame_buffer,
        .transfer_count        = (8 != RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL6_DATA_TYPE) ? RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT : (RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT * 2),
        .block_size            = 1,
    },
  #endif
  #if (8 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    {
        .transfer_mode         = DTC_TRANSFER_MODE_BLOCK,

    #if   ((1 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE) || (2 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_BYTE,
    #elif ((3 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE) || (4 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE))
        .data_size             = DTC_DATA_SIZE_WORD,
    #else
        .data_size             = DTC_DATA_SIZE_LWORD,
    #endif

        .src_addr_mode         = DTC_SRC_ADDR_INCR,
        .chain_transfer_enable = (8 == RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS) ? DTC_CHAIN_TRANSFER_DISABLE : DTC_CHAIN_TRANSFER_ENABLE,
        .chain_transfer_mode   = DTC_CHAIN_TRANSFER_NORMAL,
        .response_interrupt    = DTC_INTERRUPT_AFTER_ALL_COMPLETE,
        .repeat_block_side     = DTC_REPEAT_BLOCK_SOURCE,
        .dest_addr_mode        = DTC_DES_ADDR_INCR,
        .source_addr           = (uint32_t)NULL,
        .dest_addr             = (uint32_t)&g_rai_data_collector0_snapshot_channel7_frame_buffer,
        .transfer_count        = (8 != RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNEL7_DATA_TYPE) ? RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT : (RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT * 2),
        .block_size            = 1,
    },
  #endif
};
#endif

#if (1 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
transfer_instance_t g_rai_data_collector0_dtc =
{
    .act_source        = RM_RAI_DATA_COLLECTOR_CFG_DC0_DTC_ACT_SOURCE,
    .p_transfer_data   = &g_rai_data_collector0_dtc_transfer_data[0],
    .p_data_cfg        = NULL,
    .chain_transfer_nr = RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS,
};
#endif

/* RAI Data Collector0 */
rai_data_collector_frame_buffer_handle_t g_rai_data_collector0_frame_buf_hnd[RM_RAI_DATA_COLLECTOR_DC0_VIRT_CHANNELS];
rai_data_collector_extended_cfg_t g_rai_data_collector0_extended_cfg =
{
    .p_ping_pong_buf     = g_rai_data_collector0_frame_buf,
    .p_ping_pong_buf_hnd = g_rai_data_collector0_frame_buf_hnd,
#if (1 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    .p_transfer_info     = g_rai_data_collector0_dtc_transfer_data_cfg,
#endif
};

rai_data_collector_instance_ctrl_t g_rai_data_collector0_ctrl;

const rai_data_collector_snapshot_cfg_t g_rai_data_collector0_ss_cfg =
{
    .channels     = RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS,
    .transfer_len = RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_COUNT,
#if (1 <= RM_RAI_DATA_COLLECTOR_CFG_DC0_SNAPSHOT_CHANNELS)
    .p_timer      = &g_rai_data_collector0_timer,
    .p_transfer   = &g_rai_data_collector0_dtc,
#endif
};

const rai_data_collector_data_feed_cfg_t g_rai_data_collector0_df_cfg =
{
    .channels = RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_FEED_CHANNELS,
};

rai_data_collector_cfg_t g_rai_data_collector0_cfg =
{
    .channels           = RM_RAI_DATA_COLLECTOR_DC0_CHANNELS,
    .instance_id        = RM_RAI_DATA_COLLECTOR_CFG_DC0_ID,
    .virt_channels      = RM_RAI_DATA_COLLECTOR_DC0_VIRT_CHANNELS,
    .channel_ready_mask = 0,
    .required_frame_len = RM_RAI_DATA_COLLECTOR_CFG_DC0_FRAME_BUF_LEN,
    .p_snapshot_cfg     = &g_rai_data_collector0_ss_cfg,
    .p_data_feed_cfg    = &g_rai_data_collector0_df_cfg,
    .p_extend           = &g_rai_data_collector0_extended_cfg,
    .p_callback         = RM_RAI_DATA_COLLECTOR_CFG_DC0_DATA_READY_CALLBACK,
    .p_error_callback   = RM_RAI_DATA_COLLECTOR_CFG_DC0_ERROR_CALLBACK,
    .p_context          = NULL,
};

const rai_data_collector_instance_t g_rai_data_collector0 =
{
  .p_ctrl   = &g_rai_data_collector0_ctrl,
  .p_cfg    = &g_rai_data_collector0_cfg,
  .p_api    = &g_dc_on_rai_data_collector,
};

/* Timer callback function */
void rm_rai_data_collector_dc0_timer_callback(void * pdata)
{
    rm_rai_data_collector_dtc_end_cb (&g_rai_data_collector0_ctrl);
}

